title: David Henry
description: Fixing that thing I broke last week.
url: "https://dwhenry.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:year/:month/:day/:title/

paginate: 20
paginate_path: "/page:num/"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
